spring:

  ai:
    model:
      chat: bedrock-converse
    bedrock:
      aws:
        region: us-east-1
      converse:
        chat:
          options:
            model: amazon.nova-pro-v1:0
    mcp:
      client:
        enabled: true
        stdio:
          servers-configuration: classpath:mcp-servers-stdio.json

